services:
  qwen2:
    image: qwenllm/qwenvl:2-cu121
    container_name: qwen2
    network_mode: host
    ipc: host
    stdin_open: true    # Equivalent to -i
    tty: true           # Equivalent to -t
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids:
                - "0"
    volumes:
      - ./data:/app/data            # Example of mounting a volume
